# Generated by Django 5.2.5 on 2025-11-14 23:28

import apps.musica.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.musica.models.portada_upload_path)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, help_text='Artista responsable del álbum', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.musica.models.cancion_upload_path)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.musica.models.portada_upload_path, verbose_name='Portada')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, help_text='Álbum opcional al que pertenece la canción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='musica.album')),
                ('uploaded_by', models.ForeignKey(help_text='Usuario con rol de artista que subió la canción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Artista')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.genero')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='musica.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reproducciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Reproducción',
                'verbose_name_plural': 'Historial de Reproducciones',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='CancionFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregada_en', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='musica.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canción Favorita',
                'verbose_name_plural': 'Canciones Favoritas',
                'ordering': ['-agregada_en'],
                'unique_together': {('usuario', 'cancion')},
            },
        ),
    ]
