# Generated by Django 5.2.8 on 2025-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Artista', 'Artista'), ('Oyente', 'Oyente')], max_length=30, unique=True),
        ),
    ]
