# Generated by Django 5.2.5 on 2025-11-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_rol_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_artistico',
            field=models.CharField(blank=True, help_text='Nombre artístico para artistas', max_length=100, null=True, verbose_name='Nombre Artístico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre.'}, help_text='Requerido. 150 caracteres o menos. Puede contener espacios para artistas.', max_length=150, unique=True),
        ),
    ]
